package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbClientes generated by hbm2java
 */
public class TbClientes  implements java.io.Serializable {


     private Integer id;
     private String nit;
     private String razonSocial;
     private String telefono;
     private String celular;
     private int contacto;
     private boolean estado;
     private String direccion;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbFacturaVenta> tbFacturaVentas = new HashSet<TbFacturaVenta>(0);

    public TbClientes() {
    }

	
    public TbClientes(String nit, String razonSocial, String telefono, String celular, int contacto, boolean estado, String direccion, String creadoPor, Date creadoEn) {
        this.nit = nit;
        this.razonSocial = razonSocial;
        this.telefono = telefono;
        this.celular = celular;
        this.contacto = contacto;
        this.estado = estado;
        this.direccion = direccion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbClientes(String nit, String razonSocial, String telefono, String celular, int contacto, boolean estado, String direccion, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbFacturaVenta> tbFacturaVentas) {
       this.nit = nit;
       this.razonSocial = razonSocial;
       this.telefono = telefono;
       this.celular = celular;
       this.contacto = contacto;
       this.estado = estado;
       this.direccion = direccion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbFacturaVentas = tbFacturaVentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbFacturaVenta> getTbFacturaVentas() {
        return this.tbFacturaVentas;
    }
    
    public void setTbFacturaVentas(Set<TbFacturaVenta> tbFacturaVentas) {
        this.tbFacturaVentas = tbFacturaVentas;
    }




}


