package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbDetalleFacturaVenta generated by hbm2java
 */
public class TbDetalleFacturaVenta  implements java.io.Serializable {


     private Integer id;
     private TbFacturaVenta tbFacturaVenta;
     private TbProductoTerminado tbProductoTerminado;
     private int cantidad;
     private int vlorIva;
     private String tipoIva;
     private int vlorUnitario;
     private int vlorTotal;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;

    public TbDetalleFacturaVenta() {
    }

	
    public TbDetalleFacturaVenta(TbFacturaVenta tbFacturaVenta, TbProductoTerminado tbProductoTerminado, int cantidad, int vlorIva, String tipoIva, int vlorUnitario, int vlorTotal, String creadoPor, Date creadoEn) {
        this.tbFacturaVenta = tbFacturaVenta;
        this.tbProductoTerminado = tbProductoTerminado;
        this.cantidad = cantidad;
        this.vlorIva = vlorIva;
        this.tipoIva = tipoIva;
        this.vlorUnitario = vlorUnitario;
        this.vlorTotal = vlorTotal;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbDetalleFacturaVenta(TbFacturaVenta tbFacturaVenta, TbProductoTerminado tbProductoTerminado, int cantidad, int vlorIva, String tipoIva, int vlorUnitario, int vlorTotal, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn) {
       this.tbFacturaVenta = tbFacturaVenta;
       this.tbProductoTerminado = tbProductoTerminado;
       this.cantidad = cantidad;
       this.vlorIva = vlorIva;
       this.tipoIva = tipoIva;
       this.vlorUnitario = vlorUnitario;
       this.vlorTotal = vlorTotal;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbFacturaVenta getTbFacturaVenta() {
        return this.tbFacturaVenta;
    }
    
    public void setTbFacturaVenta(TbFacturaVenta tbFacturaVenta) {
        this.tbFacturaVenta = tbFacturaVenta;
    }
    public TbProductoTerminado getTbProductoTerminado() {
        return this.tbProductoTerminado;
    }
    
    public void setTbProductoTerminado(TbProductoTerminado tbProductoTerminado) {
        this.tbProductoTerminado = tbProductoTerminado;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getVlorIva() {
        return this.vlorIva;
    }
    
    public void setVlorIva(int vlorIva) {
        this.vlorIva = vlorIva;
    }
    public String getTipoIva() {
        return this.tipoIva;
    }
    
    public void setTipoIva(String tipoIva) {
        this.tipoIva = tipoIva;
    }
    public int getVlorUnitario() {
        return this.vlorUnitario;
    }
    
    public void setVlorUnitario(int vlorUnitario) {
        this.vlorUnitario = vlorUnitario;
    }
    public int getVlorTotal() {
        return this.vlorTotal;
    }
    
    public void setVlorTotal(int vlorTotal) {
        this.vlorTotal = vlorTotal;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


