package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbDetalleProduccion generated by hbm2java
 */
public class TbDetalleProduccion  implements java.io.Serializable {


     private int id;
     private TbDetalleProduccion tbDetalleProduccion;
     private TbProductoTerminado tbProductoTerminado;
     private int cantidad;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleProduccion> tbDetalleProduccions = new HashSet<TbDetalleProduccion>(0);

    public TbDetalleProduccion() {
    }

	
    public TbDetalleProduccion(int id, TbDetalleProduccion tbDetalleProduccion, TbProductoTerminado tbProductoTerminado, int cantidad, String creadoPor, Date creadoEn) {
        this.id = id;
        this.tbDetalleProduccion = tbDetalleProduccion;
        this.tbProductoTerminado = tbProductoTerminado;
        this.cantidad = cantidad;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbDetalleProduccion(int id, TbDetalleProduccion tbDetalleProduccion, TbProductoTerminado tbProductoTerminado, int cantidad, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleProduccion> tbDetalleProduccions) {
       this.id = id;
       this.tbDetalleProduccion = tbDetalleProduccion;
       this.tbProductoTerminado = tbProductoTerminado;
       this.cantidad = cantidad;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleProduccions = tbDetalleProduccions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TbDetalleProduccion getTbDetalleProduccion() {
        return this.tbDetalleProduccion;
    }
    
    public void setTbDetalleProduccion(TbDetalleProduccion tbDetalleProduccion) {
        this.tbDetalleProduccion = tbDetalleProduccion;
    }
    public TbProductoTerminado getTbProductoTerminado() {
        return this.tbProductoTerminado;
    }
    
    public void setTbProductoTerminado(TbProductoTerminado tbProductoTerminado) {
        this.tbProductoTerminado = tbProductoTerminado;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleProduccion> getTbDetalleProduccions() {
        return this.tbDetalleProduccions;
    }
    
    public void setTbDetalleProduccions(Set<TbDetalleProduccion> tbDetalleProduccions) {
        this.tbDetalleProduccions = tbDetalleProduccions;
    }




}


