package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbDetalleEntradaProdTerm generated by hbm2java
 */
public class TbDetalleEntradaProdTerm  implements java.io.Serializable {


     private Integer id;
     private TbEntradaProdTerminado tbEntradaProdTerminado;
     private TbProductoTerminado tbProductoTerminado;
     private int cantidad;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;

    public TbDetalleEntradaProdTerm() {
    }

	
    public TbDetalleEntradaProdTerm(TbEntradaProdTerminado tbEntradaProdTerminado, TbProductoTerminado tbProductoTerminado, int cantidad, String creadoPor, Date creadoEn) {
        this.tbEntradaProdTerminado = tbEntradaProdTerminado;
        this.tbProductoTerminado = tbProductoTerminado;
        this.cantidad = cantidad;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbDetalleEntradaProdTerm(TbEntradaProdTerminado tbEntradaProdTerminado, TbProductoTerminado tbProductoTerminado, int cantidad, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn) {
       this.tbEntradaProdTerminado = tbEntradaProdTerminado;
       this.tbProductoTerminado = tbProductoTerminado;
       this.cantidad = cantidad;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbEntradaProdTerminado getTbEntradaProdTerminado() {
        return this.tbEntradaProdTerminado;
    }
    
    public void setTbEntradaProdTerminado(TbEntradaProdTerminado tbEntradaProdTerminado) {
        this.tbEntradaProdTerminado = tbEntradaProdTerminado;
    }
    public TbProductoTerminado getTbProductoTerminado() {
        return this.tbProductoTerminado;
    }
    
    public void setTbProductoTerminado(TbProductoTerminado tbProductoTerminado) {
        this.tbProductoTerminado = tbProductoTerminado;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


