package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbEntradaProdTerminado generated by hbm2java
 */
public class TbEntradaProdTerminado  implements java.io.Serializable {


     private Integer id;
     private String creadorPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms = new HashSet<TbDetalleEntradaProdTerm>(0);

    public TbEntradaProdTerminado() {
    }

	
    public TbEntradaProdTerminado(String creadorPor, Date creadoEn) {
        this.creadorPor = creadorPor;
        this.creadoEn = creadoEn;
    }
    public TbEntradaProdTerminado(String creadorPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms) {
       this.creadorPor = creadorPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleEntradaProdTerms = tbDetalleEntradaProdTerms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCreadorPor() {
        return this.creadorPor;
    }
    
    public void setCreadorPor(String creadorPor) {
        this.creadorPor = creadorPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleEntradaProdTerm> getTbDetalleEntradaProdTerms() {
        return this.tbDetalleEntradaProdTerms;
    }
    
    public void setTbDetalleEntradaProdTerms(Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms) {
        this.tbDetalleEntradaProdTerms = tbDetalleEntradaProdTerms;
    }




}


