package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbEntradaMateriaPrima generated by hbm2java
 */
public class TbEntradaMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas = new HashSet<TbDetalleEntradaMateriaPrima>(0);

    public TbEntradaMateriaPrima() {
    }

	
    public TbEntradaMateriaPrima(String creadoPor, Date creadoEn) {
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbEntradaMateriaPrima(String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas) {
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleEntradaMateriaPrimas = tbDetalleEntradaMateriaPrimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleEntradaMateriaPrima> getTbDetalleEntradaMateriaPrimas() {
        return this.tbDetalleEntradaMateriaPrimas;
    }
    
    public void setTbDetalleEntradaMateriaPrimas(Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas) {
        this.tbDetalleEntradaMateriaPrimas = tbDetalleEntradaMateriaPrimas;
    }




}


