package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbFacturaVenta generated by hbm2java
 */
public class TbFacturaVenta  implements java.io.Serializable {


     private Integer id;
     private TbClientes tbClientes;
     private String observacion;
     private String creadoPor;
     private Date creadoEn;
     private Date modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas = new HashSet<TbDetalleFacturaVenta>(0);

    public TbFacturaVenta() {
    }

	
    public TbFacturaVenta(TbClientes tbClientes, String observacion, String creadoPor, Date creadoEn) {
        this.tbClientes = tbClientes;
        this.observacion = observacion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbFacturaVenta(TbClientes tbClientes, String observacion, String creadoPor, Date creadoEn, Date modificadoPor, Date modificadoEn, Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas) {
       this.tbClientes = tbClientes;
       this.observacion = observacion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleFacturaVentas = tbDetalleFacturaVentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbClientes getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(TbClientes tbClientes) {
        this.tbClientes = tbClientes;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public Date getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Date modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleFacturaVenta> getTbDetalleFacturaVentas() {
        return this.tbDetalleFacturaVentas;
    }
    
    public void setTbDetalleFacturaVentas(Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas) {
        this.tbDetalleFacturaVentas = tbDetalleFacturaVentas;
    }




}


