package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMateriaPrima generated by hbm2java
 */
public class TbMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private TbUbicacion tbUbicacion;
     private String referencia;
     private String descripcion;
     private String um;
     private float stock;
     private String creadorPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas = new HashSet<TbDetalleEntradaMateriaPrima>(0);
     private Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas = new HashSet<TbDetalleSalidaMateriaPrima>(0);
     private Set<TbDetalleOrdenCompra> tbDetalleOrdenCompras = new HashSet<TbDetalleOrdenCompra>(0);

    public TbMateriaPrima() {
    }

	
    public TbMateriaPrima(TbUbicacion tbUbicacion, String referencia, String descripcion, String um, float stock, String creadorPor, Date creadoEn) {
        this.tbUbicacion = tbUbicacion;
        this.referencia = referencia;
        this.descripcion = descripcion;
        this.um = um;
        this.stock = stock;
        this.creadorPor = creadorPor;
        this.creadoEn = creadoEn;
    }
    public TbMateriaPrima(TbUbicacion tbUbicacion, String referencia, String descripcion, String um, float stock, String creadorPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas, Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas, Set<TbDetalleOrdenCompra> tbDetalleOrdenCompras) {
       this.tbUbicacion = tbUbicacion;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.um = um;
       this.stock = stock;
       this.creadorPor = creadorPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleEntradaMateriaPrimas = tbDetalleEntradaMateriaPrimas;
       this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
       this.tbDetalleOrdenCompras = tbDetalleOrdenCompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbUbicacion getTbUbicacion() {
        return this.tbUbicacion;
    }
    
    public void setTbUbicacion(TbUbicacion tbUbicacion) {
        this.tbUbicacion = tbUbicacion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUm() {
        return this.um;
    }
    
    public void setUm(String um) {
        this.um = um;
    }
    public float getStock() {
        return this.stock;
    }
    
    public void setStock(float stock) {
        this.stock = stock;
    }
    public String getCreadorPor() {
        return this.creadorPor;
    }
    
    public void setCreadorPor(String creadorPor) {
        this.creadorPor = creadorPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleEntradaMateriaPrima> getTbDetalleEntradaMateriaPrimas() {
        return this.tbDetalleEntradaMateriaPrimas;
    }
    
    public void setTbDetalleEntradaMateriaPrimas(Set<TbDetalleEntradaMateriaPrima> tbDetalleEntradaMateriaPrimas) {
        this.tbDetalleEntradaMateriaPrimas = tbDetalleEntradaMateriaPrimas;
    }
    public Set<TbDetalleSalidaMateriaPrima> getTbDetalleSalidaMateriaPrimas() {
        return this.tbDetalleSalidaMateriaPrimas;
    }
    
    public void setTbDetalleSalidaMateriaPrimas(Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas) {
        this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
    }
    public Set<TbDetalleOrdenCompra> getTbDetalleOrdenCompras() {
        return this.tbDetalleOrdenCompras;
    }
    
    public void setTbDetalleOrdenCompras(Set<TbDetalleOrdenCompra> tbDetalleOrdenCompras) {
        this.tbDetalleOrdenCompras = tbDetalleOrdenCompras;
    }




}


