package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbProduccion generated by hbm2java
 */
public class TbProduccion  implements java.io.Serializable {


     private Integer id;
     private String idDptoProduccion;
     private String creadoPor;
     private Date creadoEn;
     private String observacion;
     private String modificadoPor;
     private Date modificadoEn;

    public TbProduccion() {
    }

	
    public TbProduccion(String idDptoProduccion, String creadoPor, Date creadoEn, String observacion) {
        this.idDptoProduccion = idDptoProduccion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
        this.observacion = observacion;
    }
    public TbProduccion(String idDptoProduccion, String creadoPor, Date creadoEn, String observacion, String modificadoPor, Date modificadoEn) {
       this.idDptoProduccion = idDptoProduccion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.observacion = observacion;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIdDptoProduccion() {
        return this.idDptoProduccion;
    }
    
    public void setIdDptoProduccion(String idDptoProduccion) {
        this.idDptoProduccion = idDptoProduccion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


