package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbProductoTerminado generated by hbm2java
 */
public class TbProductoTerminado  implements java.io.Serializable {


     private Integer id;
     private TbUbicacion tbUbicacion;
     private String referencia;
     private String descripcion;
     private String um;
     private int stock;
     private String creadorPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas = new HashSet<TbDetalleFacturaVenta>(0);
     private Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms = new HashSet<TbDetalleSalidaProdTerm>(0);
     private Set<TbSalidaMateriaPrima> tbSalidaMateriaPrimas = new HashSet<TbSalidaMateriaPrima>(0);
     private Set<TbDetalleProduccion> tbDetalleProduccions = new HashSet<TbDetalleProduccion>(0);
     private Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms = new HashSet<TbDetalleEntradaProdTerm>(0);

    public TbProductoTerminado() {
    }

	
    public TbProductoTerminado(TbUbicacion tbUbicacion, String referencia, String descripcion, String um, int stock, String creadorPor, Date creadoEn) {
        this.tbUbicacion = tbUbicacion;
        this.referencia = referencia;
        this.descripcion = descripcion;
        this.um = um;
        this.stock = stock;
        this.creadorPor = creadorPor;
        this.creadoEn = creadoEn;
    }
    public TbProductoTerminado(TbUbicacion tbUbicacion, String referencia, String descripcion, String um, int stock, String creadorPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas, Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms, Set<TbSalidaMateriaPrima> tbSalidaMateriaPrimas, Set<TbDetalleProduccion> tbDetalleProduccions, Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms) {
       this.tbUbicacion = tbUbicacion;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.um = um;
       this.stock = stock;
       this.creadorPor = creadorPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleFacturaVentas = tbDetalleFacturaVentas;
       this.tbDetalleSalidaProdTerms = tbDetalleSalidaProdTerms;
       this.tbSalidaMateriaPrimas = tbSalidaMateriaPrimas;
       this.tbDetalleProduccions = tbDetalleProduccions;
       this.tbDetalleEntradaProdTerms = tbDetalleEntradaProdTerms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbUbicacion getTbUbicacion() {
        return this.tbUbicacion;
    }
    
    public void setTbUbicacion(TbUbicacion tbUbicacion) {
        this.tbUbicacion = tbUbicacion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUm() {
        return this.um;
    }
    
    public void setUm(String um) {
        this.um = um;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getCreadorPor() {
        return this.creadorPor;
    }
    
    public void setCreadorPor(String creadorPor) {
        this.creadorPor = creadorPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleFacturaVenta> getTbDetalleFacturaVentas() {
        return this.tbDetalleFacturaVentas;
    }
    
    public void setTbDetalleFacturaVentas(Set<TbDetalleFacturaVenta> tbDetalleFacturaVentas) {
        this.tbDetalleFacturaVentas = tbDetalleFacturaVentas;
    }
    public Set<TbDetalleSalidaProdTerm> getTbDetalleSalidaProdTerms() {
        return this.tbDetalleSalidaProdTerms;
    }
    
    public void setTbDetalleSalidaProdTerms(Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms) {
        this.tbDetalleSalidaProdTerms = tbDetalleSalidaProdTerms;
    }
    public Set<TbSalidaMateriaPrima> getTbSalidaMateriaPrimas() {
        return this.tbSalidaMateriaPrimas;
    }
    
    public void setTbSalidaMateriaPrimas(Set<TbSalidaMateriaPrima> tbSalidaMateriaPrimas) {
        this.tbSalidaMateriaPrimas = tbSalidaMateriaPrimas;
    }
    public Set<TbDetalleProduccion> getTbDetalleProduccions() {
        return this.tbDetalleProduccions;
    }
    
    public void setTbDetalleProduccions(Set<TbDetalleProduccion> tbDetalleProduccions) {
        this.tbDetalleProduccions = tbDetalleProduccions;
    }
    public Set<TbDetalleEntradaProdTerm> getTbDetalleEntradaProdTerms() {
        return this.tbDetalleEntradaProdTerms;
    }
    
    public void setTbDetalleEntradaProdTerms(Set<TbDetalleEntradaProdTerm> tbDetalleEntradaProdTerms) {
        this.tbDetalleEntradaProdTerms = tbDetalleEntradaProdTerms;
    }




}


