package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbSalidaProdTerminado generated by hbm2java
 */
public class TbSalidaProdTerminado  implements java.io.Serializable {


     private Integer id;
     private String despachadorPara;
     private String observaciones;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms = new HashSet<TbDetalleSalidaProdTerm>(0);

    public TbSalidaProdTerminado() {
    }

	
    public TbSalidaProdTerminado(String despachadorPara, String observaciones, String creadoPor, Date creadoEn) {
        this.despachadorPara = despachadorPara;
        this.observaciones = observaciones;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbSalidaProdTerminado(String despachadorPara, String observaciones, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms) {
       this.despachadorPara = despachadorPara;
       this.observaciones = observaciones;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleSalidaProdTerms = tbDetalleSalidaProdTerms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDespachadorPara() {
        return this.despachadorPara;
    }
    
    public void setDespachadorPara(String despachadorPara) {
        this.despachadorPara = despachadorPara;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleSalidaProdTerm> getTbDetalleSalidaProdTerms() {
        return this.tbDetalleSalidaProdTerms;
    }
    
    public void setTbDetalleSalidaProdTerms(Set<TbDetalleSalidaProdTerm> tbDetalleSalidaProdTerms) {
        this.tbDetalleSalidaProdTerms = tbDetalleSalidaProdTerms;
    }




}


