package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbSalidaMateriaPrima generated by hbm2java
 */
public class TbSalidaMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private TbProductoTerminado tbProductoTerminado;
     private String dptoProducion;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas = new HashSet<TbDetalleSalidaMateriaPrima>(0);

    public TbSalidaMateriaPrima() {
    }

	
    public TbSalidaMateriaPrima(TbProductoTerminado tbProductoTerminado, String dptoProducion, String creadoPor, Date creadoEn) {
        this.tbProductoTerminado = tbProductoTerminado;
        this.dptoProducion = dptoProducion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbSalidaMateriaPrima(TbProductoTerminado tbProductoTerminado, String dptoProducion, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas) {
       this.tbProductoTerminado = tbProductoTerminado;
       this.dptoProducion = dptoProducion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbProductoTerminado getTbProductoTerminado() {
        return this.tbProductoTerminado;
    }
    
    public void setTbProductoTerminado(TbProductoTerminado tbProductoTerminado) {
        this.tbProductoTerminado = tbProductoTerminado;
    }
    public String getDptoProducion() {
        return this.dptoProducion;
    }
    
    public void setDptoProducion(String dptoProducion) {
        this.dptoProducion = dptoProducion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set<TbDetalleSalidaMateriaPrima> getTbDetalleSalidaMateriaPrimas() {
        return this.tbDetalleSalidaMateriaPrimas;
    }
    
    public void setTbDetalleSalidaMateriaPrimas(Set<TbDetalleSalidaMateriaPrima> tbDetalleSalidaMateriaPrimas) {
        this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
    }




}


