package com.soapsoft.model;
// Generated 29/10/2017 01:16:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUsuario generated by hbm2java
 */
@Entity
@Table(name="tb_usuario"
    ,catalog="soap_soft"
)
public class TbUsuario  implements java.io.Serializable {


     private int id;
     private TbRolUsuario tbRolUsuario;
     private String nombreUsuario;
     private int cedula;
     private String usuario;
     private String contrasena;
     private boolean estadoUsuario;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;

    public TbUsuario() {
    }

	
    public TbUsuario(int id, TbRolUsuario tbRolUsuario, String nombreUsuario, int cedula, String usuario, String contrasena, boolean estadoUsuario, String creadoPor, String modificadoPor, Date modificadoEn) {
        this.id = id;
        this.tbRolUsuario = tbRolUsuario;
        this.nombreUsuario = nombreUsuario;
        this.cedula = cedula;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.estadoUsuario = estadoUsuario;
        this.creadoPor = creadoPor;
        this.modificadoPor = modificadoPor;
        this.modificadoEn = modificadoEn;
    }
    public TbUsuario(int id, TbRolUsuario tbRolUsuario, String nombreUsuario, int cedula, String usuario, String contrasena, boolean estadoUsuario, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn) {
       this.id = id;
       this.tbRolUsuario = tbRolUsuario;
       this.nombreUsuario = nombreUsuario;
       this.cedula = cedula;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.estadoUsuario = estadoUsuario;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public TbRolUsuario getTbRolUsuario() {
        return this.tbRolUsuario;
    }
    
    public void setTbRolUsuario(TbRolUsuario tbRolUsuario) {
        this.tbRolUsuario = tbRolUsuario;
    }

    
    @Column(name="nombre_usuario", nullable=false, length=100)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="cedula", nullable=false)
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="usuario", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasena", nullable=false, length=65535)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="estado_usuario", nullable=false)
    public boolean isEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }

    
    @Column(name="creadoPor", nullable=false, length=50)
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creadoEn", length=10)
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }

    
    @Column(name="modificadoPor", nullable=false, length=50)
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modificadoEn", nullable=false, length=10)
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


