package com.soapsoft.model;
// Generated 24/11/2017 11:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbUsuario generated by hbm2java
 */
public class TbUsuario  implements java.io.Serializable {


     private Integer id;
     private TbRolUsuario tbRolUsuario;
     private String nombreUsuario;
     private int cedula;
     private String usuario;
     private String contrasena;
     private boolean estadoUsuario;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;

    public TbUsuario() {
    }

	
    public TbUsuario(TbRolUsuario tbRolUsuario, String nombreUsuario, int cedula, String usuario, String contrasena, boolean estadoUsuario, String creadoPor, Date creadoEn, String modificadoPor) {
        this.tbRolUsuario = tbRolUsuario;
        this.nombreUsuario = nombreUsuario;
        this.cedula = cedula;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.estadoUsuario = estadoUsuario;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
        this.modificadoPor = modificadoPor;
    }
    public TbUsuario(TbRolUsuario tbRolUsuario, String nombreUsuario, int cedula, String usuario, String contrasena, boolean estadoUsuario, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn) {
       this.tbRolUsuario = tbRolUsuario;
       this.nombreUsuario = nombreUsuario;
       this.cedula = cedula;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.estadoUsuario = estadoUsuario;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbRolUsuario getTbRolUsuario() {
        return this.tbRolUsuario;
    }
    
    public void setTbRolUsuario(TbRolUsuario tbRolUsuario) {
        this.tbRolUsuario = tbRolUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public boolean isEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


